### ISSUE TITLE
AVIF | Use all available CPU resources - parallel jobs/workers

### ISSUE THREAD

**Issue by Shanti099** [JacobDev1/xl-converter#20]
Hello,

Thank you for your great application,
i use it to convert images to Avif, but conversion speed does not use all available CPU resources (Ryzen 3900x)
and it fluctuates from 5% to 50%. so average ~25%.

Could you please add a function to select the number of parallel jobs/workers, as implemented in MegaPixel and in MegaPixel-Qt by Alkl58 (also Python language), when converting to Avif. MegaPixel convert images to Avif about ~4 times faster, by using all CPU resources.
But, your application better realised and more convenient to use.

Thank you for all your great work.

![2024-04-15_185902](https://github.com/JacobDev1/xl-converter/assets/75264617/19cf1bc3-b60e-4d61-a7a3-91e1743e512c)

**Comment by JacobDev1** [comment]
Hello,

this is not a bug.

`avifenc` encoder is the only one not being run in parallel because it simply crashes when I try to run multiple copies of it. Instead, `avifenc` receives all available threads and handles multithreading on its own.

XL Converter dynamically adjusts the number of workers, which is why it's so fast. There is no need to do it manually. Changing the number of threads will also impact the number of workers.

For example, when converting 2 images with 8 threads, XL Converter would spawn 2 parallel workers with 4 cores made available to each encoder.

Unfortunately, `avifenc` is the only encoder not being run this way.

I'll look into researching this further, but I don't promise anything.

**Comment by Shanti099** [comment]
Thank you for your reply,

i just tested MegaPixel-Qt by Alkl58 (also Python language) with avifenc [1.0.4] - 2024-02-08
used 12 workers and 24 threads without any crashes. CPU used 100%.

Hope you can find solution, 
Thank you so much for all your time and work.

**Comment by JacobDev1** [comment]
Could you please check for me the version of your encoder with `avifenc --version`? Does it say `aom`?

I remember that it only crashed sometimes...

I'll test the latest `avifenc` in parallel and have a look at the source code of the program you mentioned.

**Comment by Shanti099** [comment]
![2024-04-15_202750](https://github.com/JacobDev1/xl-converter/assets/75264617/b2f2bbfc-eaa1-4f42-85a8-ec38afe794cc)

**Comment by Shanti099** [comment]
MegaPixel-Qt had older version of avifenc, i replaced it with avifenc [1.0.4] - 2024-02-08

**Comment by JacobDev1** [comment]
Alright, thank you.

I'll post the results of my tests and research on this topic when I'm finished.

**Comment by JacobDev1** [comment]
During the initial testing I didn't see any crashes.

If no issue comes up, parallel AVIF encoding will be available in XL Converter 1.0.

Thanks for bringing my attention to this.

**Comment by Shanti099** [comment]
Great, Thank you!
