### ISSUE TITLE
Please add the option "rotate the image according to the information in EXIF" (and some more)

### ISSUE THREAD

**Issue by Ukhryuk-Hai** [JacobDev1/xl-converter#31]
And also an option, just not in the settings, but in the “Output” section “rotate by X degrees,” that is, -90, 90 and 180. And let this setting be automatically reset after one use.

This is really necessary, especially EXIF. If I convert images with **XnConvert**, this option is always enabled.

**Comment by JacobDev1** [comment]
It could be a useful feature, I'll see if I can add this.

**Comment by JacobDev1** [comment]
This is a great idea, but not feasible at the moment.

I wrote a prototype of it, and I decided I do not want to tack any more features onto the current pipeline. The backend needs to be rewritten entirely; adding more features is not sustainable or maintainable. The program uses external tool binaries (like `cjxl`) instead of image processing libraries directly. This made sense when it was just supposed to parallelize JPEG XL. I did not plan for it to become this big.

I'll be looking more into this in the future.
