### ISSUE TITLE
Please create a portable version

### ISSUE THREAD

**Issue by kuro68k** [JacobDev1/xl-converter#38]
It would be really handy to have a portable version of this app, a simple archive that can be downloaded and extracted. Thanks.

**Comment by JacobDev1** [comment]
Oh, that's a tough subject. I assume you're talking about Windows.

## Why Not?

I don't offer a portable build, because XL Converter uses the official "portable" build of ImageMagick, which requires `vc_redist` installed to run. The XL Converter installer comes bundled with that dependency.

If you don't have `vc_redist` installed, the program will run, but ImageMagick will raise DLL errors. For example, **if you're converting 1,000 files, you'll get 1,000 DLL errors to click through.**

If you're uncertain about running the installer, read through its [source code](https://github.com/JacobDev1/xl-converter/blob/stable/misc/install.iss). There is nothing to be afraid of.

I just don't want an avalanche of support requests involving DLL errors. If a backend rework happens, I'll consider publishing portable builds.

## Making a Portable Build Yourself

Below, I wrote a tutorial on how to do it yourself if you really need to. Also, please don't offer them for download, because people would cause DLL errors and blame me. I have things to do other than offer free tech support.

### With Installing

1. Install XL Converter.
2. The installation folder can be copied anywhere you'd like, but...
3. You must install [Microsoft Visual C++ Redistributable 2015 - 2022](https://aka.ms/vs/17/release/vc_redist.x64.exe) on every PC you use it on.

### Without Installing

- Extract the installer by following [my tutorial](https://codepoems.eu/posts/how-to-extract-an-inno-setup-installer/).
- You'll find `vc_redist` in the `tmp/` folder generated. `vc_redist` needs to be installed for XL Converter to run properly.

---

When I say `vc_redist` I mean Microsoft Visual C++ Redistributable 2015 - 2022

**Comment by kuro68k** [comment]
Thanks. Just an FYI, you can detect if the required Visual Studio redistributable is installed by checking for registry keys or running the `Get-InstalledVcRedist` Powershell command.

**Comment by JacobDev1** [comment]
Yes, I know that's possible and I have already poked around it.

However, I'd still be worried people would ignore the popup. The program works fine without it, and you'll only encounter those DLL errors under very specific circumstances.

**Comment by JacobDev1** [comment]
Initially, I was planning to check `Version` in `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\VisualStudio\14.0\VC\Runtimes\X64` then stop the program with a notification if entry was not present.

However, I have the following concerns:
- Adding checks like this that prevent the application from running is not a common practice.
- The implementation of this check could potentially break down in 10 - 20 years, and I might not be around to fix it.
- That version of `vc_redist` could at some point start failing to install, thus not creating the needed registry entry.
- First impressions are very important, and having to install something manually can be a hassle. XL Converter is supposed to "work out of the box" and users downloading the portable build may not be aware that it comes with some caveats. 

At the moment, you can extract the installer with `innoextract`. Portable builds may appear in the future. Still, a good idea, but more important stuff keeps popping up.
