### ISSUE TITLE
Strange behavior of the program

### ISSUE THREAD

**Issue by Ukhryuk-Hai** [JacobDev1/xl-converter#43]
Previously, when encoding JPG to JXL (lossless, not Modular), if set the parameter to "effort 10" and then enable "intelligent", the process went quickly. It seems that the second option cancels the effect of the first. But now it seems that "intelligent" has no effect on anything. Or am I misunderstanding something.

**Comment by JacobDev1** [comment]
That's because you are not losslessly recompressing JPEGs with reconstruction data anymore. It's just regular lossless transcoding, which is much slower. The way it works changed.

I put up this statement everywhere.

> CHANGES: Lossless JPEG recompression was moved to dedicated options. Please review [the changes](https://xl-docs.codepoems.eu/lossless-jpeg-recompression).

Please, read [this page](https://xl-docs.codepoems.eu/lossless-jpeg-recompression).

To get the old behavior, you have to enable "JPEG XL - Automatic JPEG Recompression". However, I recommend using the new dedicated options for this.

The reasons why I redesigned it this way it:
- Users found the previous system confusing.
- Lossless JPEG Recompression means you cannot wipe the metadata, which is a bad practice for privacy.

The intelligent effort does not use the effort you set manually. This is why the spinbox gets disabled. I checked, and intelligent effort still works the same way. For lossless, it always uses Effort 9.

**Comment by Ukhryuk-Hai** [comment]
Thanks.
