### ISSUE TITLE
GUI adds multi-language support and interface size issues

### ISSUE THREAD

**Issue by wcxu21** [JacobDev1/xl-converter#51]
### Feature Description

1. Its UI doesn't support multiple languages.
2. The software UI window size cannot be saved.

### Technical Details

Have you considered adding multi-language support in future versions, such as: xx.lng or some open source projects like Weblate to translate languages?

I believe that there should be users from many countries who will help provide translations. I am from China, and I can also provide Chinese translations for this project.

When I adjust the window size at will to better suit my working method, it will still use the default window size when I start it next time. You can consider optimizing this problem.

When the manually pulled window is large, UI size control is also a problem, which will look inconsistent.

### Existing Implementations

Thank you for your work ：-）

**Comment by JacobDev1** [comment]
Hi,

I'll see if I can get saving window location and size sorted.

Thanks for the offer to translate. Using Weblate is definitely something I'd consider. Unfortunately, at the moment, localization is not the agenda. There are more pressing matters at hand. Users keep requesting features and I cannot implement them because extending the current backend is not practical. External tools need to be swapped for an API.

Localization is something I may consider in the future. I'll re-open this issue if I need your help with it.
