### ISSUE TITLE
Transcode when using lossless conversion from JPG to JXL

### ISSUE THREAD

**Issue by RafaelLinux** [JacobDev1/xl-converter#55]
### Feature Description

JXL has a feature called ‘**lossless recompression of JPEG**’.  `cjxl` (console application) implements that feature, but it seems not to be available in `xl-converter`.  When the source is a JPEG and using lossless (`-d 0`),  output JXL will be bit-exact but smaller than original JPG. 

Is this function automatically enabled also in `xl-converter` when converting from JPG to lossless JXL? And if not, can you enable it?

Thanks

### Technical Details

Existing JPEG files can be losslessly transcoded to JPEG XL, significantly reducing their size. These can be restored into the exact same JPEG file, ensuring backward compatibility with existing JPEG-based applications. This provides a smooth transition from legacy JPEG platforms to the modern JPEG XL. Both the transcoding and restoration are computationally efficient.

### Existing Implementations

cjxl -d 0

**Comment by JacobDev1** [comment]
XL Converter already has that. Pick "Lossless JPEG Recompression" from the format selector and feed it a JPEG. To reverse it, pick "JPEG Reconstruction", and feed it a JXL.

Doing this when "Lossless" is checked with "JPEG XL" by default would be a bad practice, as it prevents metadata from being removed. You can optionally have it work that way by enabling "JPEG XL - Automatic JPEG XL Recompression" in the Settings -> Conversion.

**Comment by RafaelLinux** [comment]
IMHO, it should be available under ‘Format’ when selecting ‘JPEG XL’. After all, the result is a JXL file, not a JPG file, and for less advanced users it creates confusion. In fact, that's why I didn't find this option, because I was expecting it as ‘Transcode JPG’ or something similar but as a JXL option. 

The same could apply for ‘JPG reconstruction’, but in this case, it would be clearer if it was in ‘JPEG’.

**Comment by JacobDev1** [comment]
XL Converter was carefully designed this way to stop users from hurting themselves.

There are things to consider:
- This is a new feature. Users will be confused about it either way. Having them use something they don't understand will cause more problems than it solves.
- Metadata cannot be wiped to fully reconstruct a JPEG. This is a privacy concern users would find out the hard way.
- No user should expect "Lossless" in JPEG XL to perform "Lossless JPEG Recompression" by default. No other GUI software does it this way.
- Making users used to non-standard behavior creates false expectations and cognitive friction.
- Command line tools have different expected behavior.
- "JPEG Reconstruction" cannot be in "JPEG" because you could accidentally re-encode (and ruin) your image.
- New users are not meant to find this option easily, as it enables a non-standard behavior.
- The format tab must only contain the essentials.

I explained how it works in [the manual](https://xl-docs.codepoems.eu/lossless-jpeg-recompression).

The next update will change "Lossless JPEG Recompression" to "Lossless JPEG Transcoding" as per the [whitepaper](https://ds.jpeg.org/whitepapers/jpeg-xl-whitepaper.pdf). Both are correct and officially used with a different emphasis.

XL Converter allows you to do all sorts of advanced things while being easy to use. This comes with certain design decisions.

**Comment by RafaelLinux** [comment]
> XL Converter was carefully designed this way to stop users from hurting themselves.
> 
> There are things to consider:
> 
>     * This is a new feature. Users will be confused about it either way. Having them use something they don't understand will cause more problems than it solves.
I understand that when you talk about ‘new feature’ you mean that you have recently added it to your application, because you know that this functionality of JXL is one of its features since its first versions. 
>     * Metadata cannot be wiped to fully reconstruct a JPEG. This is a privacy concern users would find out the hard way.
About metadata, taking into account that JXL is nowadays more a format to store than to publish (only Safari can display it, so nobody is going to publish in JXL) keeping metadata in JXL is not a problem. I also don't think that anyone who cares about metadata will reconvert from JXL to JPG and not remove the metadata from JXL.  
>     * No user should expect "Lossless" in JPEG XL to perform "Lossless JPEG Recompression" by default. No other GUI software does it this way.
Precisely because other converters don't even mention transcoding, that's why I was asking you about it, being a converter that uses more modern formats.
>     * Making users used to non-standard behavior creates false expectations and cognitive friction.
In that respect, I can only say that we are talking about assumptions. Every user is different and their knowledge and expectations are different. 
>     * Command line tools have different expected behavior.
In fact, only cjxl implements the functionality, so there is not much to choose from or compare. Not even ImageMagick (at the moment) implements it.
>     * "JPEG Reconstruction" cannot be in "JPEG" because you could accidentally re-encode (and ruin) your image.
This would not be the case if, following the idea of making it an option available when choosing JPG output, it would only be available if the original image is JXL. 
>     * New users are not meant to find this option easily, as it enables a non-standard behavior.
What I liked about your application is that it is an application focused on modern formats, which will only be searched by those who know the characteristics of these formats and will therefore fully understand the options available for each format. Moreover, Krita implements one of the most advanced dialogue boxes when exporting to WebP that you won't find in other programs, and I was the one who suggested certain changes to achieve the expected results with certain types of images (above all, containing text and contrasting flat colours).  
>     * The format tab must only contain the essentials.
I fully understand your approach, seeking perhaps, as you rightly say, not to complicate matters too much for the user who is not familiar with the formats. The problem that I do perceive is that the selection button mixes image formats (JXL, PNG, AVIF, JPG, WebP) with format options ("Losless JPEG recompression", "JPEG reconstruction") and multiformat export ("Smallest lossless"). I understand that in order to simplify the programming, you have preferred to do it this way, because leaving only the selection of real formats available (JPG .... WebP) and enabling or disabling the possible options of each one depending on the input image format, requires more programming and time, and this effort must be valued.
I understand that in order to simplify the programming, you have preferred to do it this way, because leaving only the selection of real formats available (JPG .... WebP) and enabling or disabling the possible options of each one depending on the input image format, requires more programming and time, and this effort must be valued.
> I explained how it works in [the manual](https://xl-docs.codepoems.eu/lossless-jpeg-recompression).
Moreover, if I already congratulated you for documenting each option in such detail (something that very few programmers do), I also have to congratulate you and thank you for your online manual, which clears the doubts of any new user about the use of the program, as well as about the formats and their options.
> The next update will change "Lossless JPEG Recompression" to "Lossless JPEG Transcoding" as per the [whitepaper](https://ds.jpeg.org/whitepapers/jpeg-xl-whitepaper.pdf). Both are correct and officially used with a different emphasis.
> 
> XL Converter allows you to do all sorts of advanced things while being easy to use. This comes with certain design decisions.

I am sure that, from your point of view, mixing “Format” with non-format options in the interface is the ideal way you have thought to make it easier for users to use and you are not going to change it, but from the formal point of view, from my point of view it creates more confusion to the user and his concept of “Format”.

Thank you for reading me and sorry for being heavy  ;)

I close the thread, because you already solved my doubt, which came precisely from the knowledge of the JXL format and waiting to find the transcoding option among those available when selecting “JXL”.

**Comment by JacobDev1** [comment]
- I meant "new feature" in the sense of not being widely used or commonly understood.
- JPEG XL is designed as a web-friendly format for publishing. It will hopefully become that one day.
- Special features are meant to have a slight learning curve so users don't use them without understanding them.
- The exact naming of the "Format" selector may change in the future. It's hard to find a suitable alternative.

Users complained about unpredictable output and confusion with "Lossless JPEG Transcoding" being tightly integrated with other formats. This was already done this way before.

Single-purpose options seem like a better idea. They offer safeguards, predictable behavior, and clear expectations. They also make "JPEG XL" and "JPEG" simpler because extra features are not immediately exposed. A short learning curve offers long-term benefits in this case.

**Comment by RafaelLinux** [comment]
> * I meant "new feature" in the sense of not being widely used or commonly understood.

I think that for those of us who have been following the evolution of the format for more than half a year - and who are most interested in taking advantage of its options - this is not a new feature. It is precisely one of those amazing features that is why we opted for JXL (as of today, especially those of us photographers who process RAW). 
> 
>     * JPEG XL is designed as a web-friendly format for publishing. It will hopefully become that one day.

Surprisingly, Mozilla does not have the same interest as we do in implementing JXL. It won't do anything about it until one of its biggest donors (Google) steps forward. And Google won't do it precisely because they had JPEG LI in the oven, which will be accepted (bets are on) first by Google's engine and then by Firefox.

>     * Special features are meant to have a slight learning curve so users don't use them without understanding them.
> 
>     * The exact naming of the "Format" selector may change in the future. It's hard to find a suitable alternative.
> 
> 
> Users complained about unpredictable output and confusion with "Lossless JPEG Transcoding" being tightly integrated with other formats. This was already done this way before.
> 
> Single-purpose options seem like a better idea. They offer safeguards, predictable behavior, and clear expectations. They also make "JPEG XL" and "JPEG" simpler because extra features are not immediately exposed. A short learning curve offers long-term benefits in this case.
