### ISSUE TITLE
Bug? on xl recompression

### ISSUE THREAD

**Issue by dill-shower** [JacobDev1/xl-converter#64]
### Version

1.0.2

### OS

Linux

### Description

I'm not sure if this can be classified as a bug, but xl-converter is unable to perform JPEG lossless recompression if the image extension is incorrectly specified as another format (PNG).

### Steps to Reproduce

Take a JPEG file and simply rename it, changing its extension to PNG.

Insert the file into xl-converter, selecting JPEG XL as the output format with automatic JPEG lossless recompression.

Receive an error: "Output file not found."

### Expected Result

xl-converter should recognize that the actual file extension is JPEG and process it accordingly

### Current Result

Output file not found 

### Input Formats

jpg

### Output Format

Lossless recompension

**Comment by JacobDev1** [comment]
This is not a bug.

XL Converter relies on file extensions to detect file types. The tools relying on magic numbers (`jxlinfo`, `cjxl`, `djxl`) are used later.

The following JPEG types are supported:

```
 ["jpg", "jpeg", "jfif", "jif", "jpe"]
```

I may also add `jfi` in the future.

Because encoding is done via external tools, file extensions are used to redirect images to appropriate encoders/decoders.

This is a marginal issue and I don't think it necessitates a redesign.

There are some quirks and limitations to the way integration is done. This topic is quite nuanced. I may bring this up in the future if people are curious. The explanation is long and tiresome though.

**Comment by Ukhryuk-Hai** [comment]
@dill-shower You can use a special utility **TrID** (for Windows), which can scan the folder, analyze the files and change the extension to the correct one.
