### ISSUE TITLE
Saving settings to disk occurs only when exit the program correctly.

### ISSUE THREAD

**Issue by Ukhryuk-Hai** [JacobDev1/xl-converter#65]
I noticed that in the event of a forced interruption of the program process (computer froze + reset button, etc.), the settings remain the same as at the time of the start before last. (I hope Google translated it correctly). This can lead to a situation when the user is involuntarily misled and continues the conversion incorrectly.

That is why I suggest saving the settings to disk immediately after changing them.

**Comment by JacobDev1** [comment]
The settings are indeed saved only when the program closes.

Having settings saved after every option change would require a lot of work. Saving it periodically would mean saving 3 JSON files every 10 or so seconds, which I'm not convinced is such a good idea.

I don't feel like this is needed in the production build.

If you need specific features, consider modifying the program yourself. You already know how to run Python scripts so this should not be that difficult. I maintain detailed build instructions in case someone needs to make a personal build.

**Comment by Ukhryuk-Hai** [comment]
Ok, then how about adding a "save settings" button? I hope you won't find it too problematic.

I'm an ordinary person who likes to test new formats (for example, DjVu, BPG, and now JXL), I don't know how to modify such a complex code. This time I'm trying to make your program better.

**Comment by JacobDev1** [comment]
I understand why autosaving would be useful. There are just way more important features to work on at the moment.

A save button would mislead users into thinking it needs to be pressed for settings to get saved. UI/UX needs to stay consistent.

Right now, autosaving is too time-consuming to justify implementation.
- Widget manager would need a major overhaul to support emitting a signal like `any_widget_state_changed`. Every widget would also need a flag to account for exceptions.
- It requires a separate thread performing writes to prevent UI from freezing.
- A cache is needed to prevent frequent disk writes. Otherwise, it could get annoying when run from an HDD.

There are much simpler solutions, but the one I merge into `stable` must meet a certain standard. Autosaving might get more attention in the future.

**Comment by Ukhryuk-Hai** [comment]
How about this idea: autosave will happen at the moment of conversion start? Of course, not every time, but only if the settings have been changed since the last save. I think this is a good compromise and you will have a hard time finding an argument against it.

**Comment by JacobDev1** [comment]
I was going to offer this as a partial solution later on. I didn't comment on it, because I like to prototype things first. I'm currently knee-deep into a major `main.py` rework, which is where this code would land. It may take some time before I get to it.

Why do you never use templates? You've ignored my polite suggestions to use them on numerous occasions. If you had used the "Bug Report" template, my answer would be different.

**Comment by Ukhryuk-Hai** [comment]
The purpose of a template is to reduce the randomness of the information provided by the user and to structure it. I think I formulate the essence of the idea clearly enough to avoid resorting to such means. In addition, templates always limit the ability to express a thought and force the user to fill in unnecessary text input fields.

**Comment by JacobDev1** [comment]
I added saving on the convert button press along with a caching system.

Free-form issues are reserved for programmers discussing libraries.

My motivation for adding templates was to avoid wasting so much time on deciphering low-quality ambiguous descriptions and avoiding back-and-forth. This is unproductive and tantamount to doing unpaid tech support.

Since introducing templates, I found the issues I received much easier to understand.

I can assure you there are no unnecessary fields in the "Bug Report" template. It's incredibly brief. A user may not think so, but a user is typically not a developer.

In this particular case, a template would indirectly tell me what the program was doing during the system reset. This would allow me to skip this entire conversation and tell you "Yes, saving will be done when conversion starts".

Templates don't limit expression. You can express yourself in the "Additional Information" section.
