### ISSUE TITLE
The program does not always show the correct time until the end of the conversion.

### ISSUE THREAD

**Issue by Ukhryuk-Hai** [JacobDev1/xl-converter#69]
### Version

latest

### OS

Windows

### Description

If start the conversion, wait a few minutes (for me it was about 15), press the "Cancel" button and press "Convert" again, the program will quickly skip those files that have already been converted. And at the same time, the program logic will consider that the time spent on skipping should also be taken into account when further calculating the remaining time. That is, the program will show that there are only a few seconds left until the end of the conversion. Which is obviously far from the truth.

It is best if the time is calculated based on the last few converted files, approximately 10-50.

### Steps to Reproduce

some text

### Expected Result

some text

### Current Result

some text

### Input Formats

doesn't matter

### Output Format

doesn't matter

**Comment by JacobDev1** [comment]
Fixed. Skipped items will be accounted for in the next version.

For estimated time left, I wrote an algorithm based on the exponential moving average (EMA) with an alpha of 0.1.

$$
EMA_t = \alpha \cdot x_t + (1 - \alpha) \cdot EMA_{t-1}
$$

For the current alpha of 0.1, 90% of significance is given to the last 22 completed items.

$$
(1 - \alpha)^n < 0.1
$$

$$
0.9^n < 0.1
$$

$$
\log(0.9^n) < \log(0.1)
$$

$$
n \cdot \log(0.9) < \log(0.1)
$$

$$
n > \frac{\log(0.1)}{\log(0.9)}
$$

$$
n \approx 22
$$

There is also a timer subtracting time every second, so this value is just an approximation.

The next version will have an improved accuracy due to shuffling item order before processing. This makes time complexity distribution more even.
