### ISSUE TITLE
JPEG recompression anti-lossy

### ISSUE THREAD

**Issue by kupitmanzi** [JacobDev1/xl-converter#71]
### Feature Description

After recompression jpeg into jxl, do automatic recompression back and compare the hashes of the original and produced from JXL jpeg.
Sometimes jxl produce corrupted jpegs that are not completely lossless. https://github.com/libjxl/libjxl/issues/3882 (i have bigger %, 1-5%, no hdr or something weird)

### Technical Details

Compare the hashes of the original and produced from JXL jpeg. If hashes difference save original file. (add it like additional setting)

### Existing Implementations

nobody

**Comment by JacobDev1** [comment]
I'll add this feature to my TODO list. That being said, users shouldn't worry about checksums. The transcoding process is very reliable.

The libjxl/libjxl#3882 issue is not about checksums or corruption.
- A user tried transcoding a JPEG image with too much tail data. The image was correctly rejected due to limits in the specs.
- The user mistakenly claimed an image failed to reconstruct instead of transcode. 
- The user manually disabled reconstruction data which, obviously, made reconstruction impossible. The output is correct and not corrupted.

Cases where a JPEG image was successfully transcoded (with reconstruction data) and couldn't be reconstructed back to JPEG are extremely rare.

It's common to encounter JPEG images that will be rejected by `cjxl` during lossless transcoding. There are limits to the specs. That's quite alright. If you have any JPEG images that won't transcode, you can clean them with `jpegtran`:

Installation:

- Windows
    - Install [Scoop](https://scoop.sh/)
    - `scoop install main/libjpeg-turbo`
- Linux: `sudo apt install libjpeg-progs`

Usage:

```
jpegtran -copy all -optimize input.jpg > output.jpg
```

The `output.jpg` should transcode without issues.

**Comment by kupitmanzi** [comment]
I mean lossless(lossless reconversion) jpeg to jxl, when comparing give SSIM different file. It would be nice to add output file validation, just in case. Thanks.
p.s(wrong report link, didn't see that it was a different problem, my mistake)

**Comment by JacobDev1** [comment]
I've added it. This feature will appear in the next version.

It'll verify that the original JPEG image can be reconstructed with a matching BLAKE2b checksum.

It does come with a slight speed penalty. Its usefulness will be rather minimal, because lossless JPEG transcoding is very reliable in `cjxl`. However, I do understand people want reassurance.
